SET NOCOUNT , XACT_ABORT ON;
BEGIN TRY
	BEGIN TRANSACTION;

	/* CODE BLOCK */
		CREATE TABLE _TEST(Id int)
		INSERT INTO _TEST VALUES (1),(2),(3),(4)
		SELECT * FROM _TEST
	/* CODE BLOCK */

	ROLLBACK TRANSACTION;
END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0
    BEGIN
        ROLLBACK TRANSACTION;
    END;

END CATCH;
SET NOCOUNT , XACT_ABORT OFF;


